/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


export type Id = number;

export type AgentKind = "Ai" | "Logic";

export type OutFormat = "Text" | "Json";
/**
 * Unix Epoch time in Micosecond precision
 */

export type UnixTimeUs = number;

export type DSourceKind = "File" | "Folder" | "GhRepo" | "GgXls" | "GgDoc" | "MsXls" | "MsDoc" | "Unknown";



export interface Agent {
	chain?: string | null;
	desc?: string | null;
	id: Id;
	inst?: string | null;
	kind: AgentKind;
	model?: string | null;
	name: string;
	out_format?: OutFormat | null;
	prompt_tmpl?: string | null;
	provider?: string | null;
	space_default: boolean;
	uid: string;
}

export interface AgentForCreate {
	desc?: string | null;
	inst?: string | null;
	kind?: AgentKind | null;
	model?: string | null;
	name: string;
	out_format?: OutFormat | null;
	prompt_tmpl?: string | null;
	provider?: string | null;
	space_default?: boolean | null;
}

export interface AgentLite {
	id: Id;
	name: string;
}

export interface AgentForUpdate {
	chain?: string | null;
	desc?: string | null;
	inst?: string | null;
	model?: string | null;
	name?: string | null;
	out_format?: OutFormat | null;
	prompt_tmpl?: string | null;
	provider?: string | null;
	space_default?: boolean | null;
}

export interface Conv {
	cfile_id?: Id | null;
	conv_ref_id?: Id | null;
	id: Id;
	last_open?: number | null;
	space_id: Id;
	title?: string | null;
	uid: string;
	work_tdone?: UnixTimeUs | null;
	work_tnew?: UnixTimeUs | null;
}

export interface Drive {
	id: Id;
	name: string;
	uid: string;
}

export interface DriveForCreate {
	name: string;
}

export interface DriveForUpdate {
	name?: string | null;
}

export interface DSource {
	detail?: unknown;
	drive_id: Id;
	id: Id;
	kind: DSourceKind;
	name: string;
	rref: string;
	uid: string;
}

export interface DSourceForCreate {
	detail?: unknown;
	drive_id: Id;
	rref: string;
}
/**
 * Note 1: Here, we do not want to update the "rref" as we might already have some data on disk with the DSource.uid, and this will cause problems. Note 2: However, as of now, it's not clear if a DSource will have a local folder/file or if it is the `DItem` or `DFile` that will have those.
 */

export interface DSourceForUpdate {
	detail?: unknown;
}

export interface Space {
	agent_id?: Id | null;
	id: Id;
	last_open?: number | null;
	name: string;
	uid: string;
}

export interface SpaceForCreate {
	agent_id?: Id | null;
	name: string;
}

export interface SpaceForUpdate {
	agent_id?: Id | null;
	name?: string | null;
}
