"$schema" = "./schemas/desktop-schema.json"
identifier = "main-capability"
description = "Capability for the main window"
windows = [ "*" ]
permissions = [
  "path:default",
  "event:default",
  "window:default",
  "app:default",
  "resources:default",
  "menu:default",
  "tray:default",
  "window:default",
  "window:allow-start-dragging",
  "dialog:allow-open",
]